using System;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace JD.Domain.ManifestGeneration.Generator;

/// <summary>
/// Emits C# source code for DomainManifest instances.
/// </summary>
internal sealed class ManifestEmitter
{
    private readonly string _manifestName;
    private readonly string _namespace;
    private readonly string _version;

    public ManifestEmitter(string manifestName, string @namespace, string version)
    {
        _manifestName = manifestName;
        _namespace = @namespace;
        _version = version;
    }

    /// <summary>
    /// Emits the complete manifest source code.
    /// </summary>
    public string EmitManifest(
        ImmutableArray<EntityInfo> entities,
        ImmutableArray<ValueObjectInfo> valueObjects)
    {
        var sb = new StringBuilder();

        // File header
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        // Namespace
        sb.AppendLine($"namespace {_namespace};");
        sb.AppendLine();

        // Using directives
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using JD.Domain.Abstractions;");
        sb.AppendLine();

        // Class declaration
        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// Auto-generated manifest for {_manifestName}.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("[System.CodeDom.Compiler.GeneratedCode(\"JD.Domain.ManifestGeneration.Generator\", \"1.0.0\")]");
        sb.AppendLine($"public static class {_manifestName}Manifest");
        sb.AppendLine("{");

        // GeneratedManifest property
        sb.AppendLine("    /// <summary>");
        sb.AppendLine($"    /// Gets the auto-generated domain manifest for {_manifestName}.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static DomainManifest GeneratedManifest { get; } = new()");
        sb.AppendLine("    {");
        sb.AppendLine($"        Name = \"{_manifestName}\",");
        sb.AppendLine($"        Version = new Version(\"{_version}\"),");
        sb.AppendLine("        Sources = new List<SourceInfo>");
        sb.AppendLine("        {");
        sb.AppendLine("            new SourceInfo");
        sb.AppendLine("            {");
        sb.AppendLine("                Type = \"Generator\",");
        sb.AppendLine("                Location = \"JD.Domain.ManifestGeneration.Generator\"");
        sb.AppendLine("            }");
        sb.AppendLine("        },");
        sb.AppendLine("        CreatedAt = new DateTimeOffset(1970, 1, 1, 0, 0, 0, TimeSpan.Zero),");

        // Entities
        if (!entities.IsEmpty)
        {
            sb.AppendLine("        Entities = new List<EntityManifest>");
            sb.AppendLine("        {");

            foreach (var entity in entities
                .OrderBy(e => e.Name, StringComparer.Ordinal)
                .ThenBy(e => e.FullTypeName, StringComparer.Ordinal))
            {
                EmitEntity(sb, entity);
            }

            sb.AppendLine("        },");
        }

        // Value Objects
        if (!valueObjects.IsEmpty)
        {
            sb.AppendLine("        ValueObjects = new List<ValueObjectManifest>");
            sb.AppendLine("        {");

            foreach (var vo in valueObjects
                .OrderBy(v => v.Name, StringComparer.Ordinal)
                .ThenBy(v => v.FullTypeName, StringComparer.Ordinal))
            {
                EmitValueObject(sb, vo);
            }

            sb.AppendLine("        },");
        }

        sb.AppendLine("    };");
        sb.AppendLine("}");

        return sb.ToString();
    }

    /// <summary>
    /// Emits an entity manifest entry.
    /// </summary>
    private static void EmitEntity(StringBuilder sb, EntityInfo entity)
    {
        sb.AppendLine("            new EntityManifest");
        sb.AppendLine("            {");
        sb.AppendLine($"                Name = \"{entity.Name}\",");
        sb.AppendLine($"                TypeName = \"{EscapeString(entity.FullTypeName)}\",");

        if (!string.IsNullOrEmpty(entity.Namespace))
        {
            sb.AppendLine($"                Namespace = \"{EscapeString(entity.Namespace!)}\",");
        }

        if (!string.IsNullOrEmpty(entity.Description))
        {
            sb.AppendLine($"                Description = \"{EscapeString(entity.Description!)}\",");
        }

        if (!string.IsNullOrEmpty(entity.TableName))
        {
            sb.AppendLine($"                TableName = \"{EscapeString(entity.TableName!)}\",");
        }

        if (!string.IsNullOrEmpty(entity.Schema))
        {
            sb.AppendLine($"                SchemaName = \"{EscapeString(entity.Schema!)}\",");
        }

        // Properties
        if (!entity.Properties.IsEmpty)
        {
            sb.AppendLine("                Properties = new List<PropertyManifest>");
            sb.AppendLine("                {");

            foreach (var prop in entity.Properties
                .OrderBy(p => p.Name, StringComparer.Ordinal)
                .ThenBy(p => p.TypeName, StringComparer.Ordinal))
            {
                EmitProperty(sb, prop);
            }

            sb.AppendLine("                },");

            // Key properties (inferred from [Key] attribute)
            var keyProps = entity.Properties.Where(p => p.IsKey).OrderBy(p => p.Name, StringComparer.Ordinal).ToArray();
            if (keyProps.Length > 0)
            {
                sb.Append("                KeyProperties = new List<string> { ");
                sb.Append(string.Join(", ", keyProps.Select(p => $"\"{p.Name}\"")));
                sb.AppendLine(" },");
            }
        }

        sb.AppendLine("            },");
    }

    /// <summary>
    /// Emits a value object manifest entry.
    /// </summary>
    private static void EmitValueObject(StringBuilder sb, ValueObjectInfo vo)
    {
        sb.AppendLine("            new ValueObjectManifest");
        sb.AppendLine("            {");
        sb.AppendLine($"                Name = \"{vo.Name}\",");
        sb.AppendLine($"                TypeName = \"{EscapeString(vo.FullTypeName)}\",");

        if (!string.IsNullOrEmpty(vo.Namespace))
        {
            sb.AppendLine($"                Namespace = \"{EscapeString(vo.Namespace!)}\",");
        }

        if (!string.IsNullOrEmpty(vo.Description))
        {
            sb.AppendLine($"                Description = \"{EscapeString(vo.Description!)}\",");
        }

        // Properties
        if (!vo.Properties.IsEmpty)
        {
            sb.AppendLine("                Properties = new List<PropertyManifest>");
            sb.AppendLine("                {");

            foreach (var prop in vo.Properties
                .OrderBy(p => p.Name, StringComparer.Ordinal)
                .ThenBy(p => p.TypeName, StringComparer.Ordinal))
            {
                EmitProperty(sb, prop);
            }

            sb.AppendLine("                },");
        }

        sb.AppendLine("            },");
    }

    /// <summary>
    /// Emits a property manifest entry.
    /// </summary>
    private static void EmitProperty(StringBuilder sb, PropertyInfo property)
    {
        sb.AppendLine("                    new PropertyManifest");
        sb.AppendLine("                    {");
        sb.AppendLine($"                        Name = \"{property.Name}\",");
        sb.AppendLine($"                        TypeName = \"{EscapeString(property.TypeName)}\",");
        sb.AppendLine($"                        IsRequired = {(property.IsRequired ? "true" : "false")},");

        if (property.MaxLength.HasValue)
        {
            sb.AppendLine($"                        MaxLength = {property.MaxLength.Value},");
        }

        sb.AppendLine("                    },");
    }

    /// <summary>
    /// Escapes special characters in strings for C# code.
    /// </summary>
    private static string EscapeString(string value)
    {
        return value.Replace("\\", "\\\\").Replace("\"", "\\\"");
    }
}
