using JD.Domain.Abstractions;
using JD.Domain.Generators.Core;
using Microsoft.CodeAnalysis.CSharp;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using Xunit;

namespace JD.Domain.Tests.Unit.Generators;

public class GeneratorsTests
{
    [Fact]
    public void CodeBuilder_AppendsLine_WithCorrectIndentation()
    {
        var builder = new CodeBuilder();
        builder.AppendLine("line1");
        builder.Indent();
        builder.AppendLine("line2");
        builder.Unindent();
        builder.AppendLine("line3");

        var result = builder.ToString();
        
        Assert.Contains("line1", result);
        Assert.Contains("    line2", result);
        Assert.Contains("line3", result);
    }

    [Fact]
    public void CodeBuilder_OpenAndCloseBrace_WorksCorrectly()
    {
        var builder = new CodeBuilder();
        builder.AppendLine("class Test");
        builder.OpenBrace();
        builder.AppendLine("public int Value { get; set; }");
        builder.CloseBrace();

        var result = builder.ToString();
        
        Assert.Contains("class Test", result);
        Assert.Contains("{", result);
        Assert.Contains("    public int Value { get; set; }", result);
        Assert.Contains("}", result);
    }

    [Fact]
    public void CodeBuilder_BeginAndEndClass_GeneratesProperStructure()
    {
        var builder = new CodeBuilder();
        builder.BeginClass("TestClass", "public", "sealed");
        builder.AppendLine("public int Value { get; set; }");
        builder.EndClass();

        var result = builder.ToString();
        
        Assert.Contains("public sealed class TestClass", result);
        Assert.Contains("    public int Value { get; set; }", result);
    }

    [Fact]
    public void CodeBuilder_BeginAndEndNamespace_GeneratesProperStructure()
    {
        var builder = new CodeBuilder();
        builder.BeginNamespace("Test.Namespace");
        builder.AppendLine("public class Test {}");
        builder.EndNamespace();

        var result = builder.ToString();
        
        Assert.Contains("namespace Test.Namespace", result);
        Assert.Contains("    public class Test {}", result);
    }

    [Fact]
    public void CodeBuilder_AutoGeneratedHeader_IncludesExpectedContent()
    {
        var builder = new CodeBuilder();
        builder.AutoGeneratedHeader("TestGenerator", "1.0.0");

        var result = builder.ToString();
        
        Assert.Contains("<auto-generated>", result);
        Assert.Contains("Generated by TestGenerator", result);
        Assert.Contains("Version: 1.0.0", result);
        Assert.Contains("#nullable enable", result);
    }

    [Fact]
    public void GeneratorUtilities_ComputeHash_ReturnsSameHashForSameContent()
    {
        var content = "test content";
        var hash1 = GeneratorUtilities.ComputeHash(content);
        var hash2 = GeneratorUtilities.ComputeHash(content);

        Assert.Equal(hash1, hash2);
        Assert.NotEmpty(hash1);
    }

    [Fact]
    public void GeneratorUtilities_ToIdentifier_ConvertsInvalidCharacters()
    {
        var result = GeneratorUtilities.ToIdentifier("Test-Name.With Invalid");
        
        Assert.Equal("Test_Name_With_Invalid", result);
    }

    [Fact]
    public void GeneratorUtilities_ToIdentifier_HandlesLeadingDigit()
    {
        var result = GeneratorUtilities.ToIdentifier("123Test");
        
        Assert.StartsWith("_", result);
    }

    [Fact]
    public void GeneratorUtilities_EscapeStringLiteral_EscapesSpecialCharacters()
    {
        var result = GeneratorUtilities.EscapeStringLiteral("test\nvalue\"quote");
        
        Assert.Contains("\\n", result);
        Assert.Contains("\\\"", result);
        Assert.StartsWith("\"", result);
        Assert.EndsWith("\"", result);
    }

    [Fact]
    public void GeneratorUtilities_GenerateFileName_CreatesValidFileName()
    {
        var result = GeneratorUtilities.GenerateFileName("TestEntity", "Configuration");
        
        Assert.Equal("TestEntity.Configuration.g.cs", result);
    }

    [Fact]
    public void GeneratorUtilities_NormalizeLineEndings_NormalizesAllTypes()
    {
        var input = "line1\r\nline2\rline3\nline4";
        var result = GeneratorUtilities.NormalizeLineEndings(input);
        
        var expectedLineCount = 4;
        var actualLineCount = result.Split(new[] { Environment.NewLine }, StringSplitOptions.None).Length;
        
        Assert.Equal(expectedLineCount, actualLineCount);
    }

    [Fact]
    public void GeneratorPipeline_Add_AddsGenerator()
    {
        var pipeline = new GeneratorPipeline();
        var generator = new TestGenerator();
        
        pipeline.Add(generator);
        
        Assert.Single(pipeline.Generators);
        Assert.Same(generator, pipeline.Generators[0]);
    }

    [Fact]
    public void GeneratorPipeline_Execute_CallsAllGenerators()
    {
        var pipeline = new GeneratorPipeline();
        var generator1 = new TestGenerator();
        var generator2 = new TestGenerator();
        
        pipeline.Add(generator1).Add(generator2);
        
        var manifest = new DomainManifest { Name = "Test", Version = new Version(1, 0, 0) };
        var compilation = CSharpCompilation.Create("Test");
        var context = new GeneratorContext
        {
            Manifest = manifest,
            Compilation = compilation,
            CancellationToken = CancellationToken.None
        };
        
        var results = pipeline.Execute(context).ToList();
        
        Assert.Equal(2, results.Count);
    }

    [Fact]
    public void GeneratedFile_HintName_ReturnsSameAsFileName()
    {
        var file = new GeneratedFile
        {
            FileName = "Test.g.cs",
            Content = "// test"
        };
        
        Assert.Equal(file.FileName, file.HintName);
    }

    [Fact]
    public void BaseCodeGenerator_CreateGeneratedFile_ComputesHash()
    {
        var generator = new TestGenerator();
        var content = "test content";
        
        var file = generator.CreateGeneratedFilePublic("Test.g.cs", content);
        
        Assert.NotNull(file.ContentHash);
        Assert.NotEmpty(file.ContentHash);
    }

    [Fact]
    public void BaseCodeGenerator_CreateCodeBuilder_IncludesHeader()
    {
        var generator = new TestGenerator();
        var builder = generator.CreateCodeBuilderPublic("1.0.0");
        
        var result = builder.ToString();
        
        Assert.Contains("<auto-generated>", result);
        Assert.Contains("TestGenerator", result);
    }

    private class TestGenerator : BaseCodeGenerator
    {
        public override string Name => "TestGenerator";

        public override IEnumerable<GeneratedFile> Generate(GeneratorContext context, CancellationToken cancellationToken = default)
        {
            yield return new GeneratedFile
            {
                FileName = "Test.g.cs",
                Content = "// Generated"
            };
        }

        public GeneratedFile CreateGeneratedFilePublic(string fileName, string content)
        {
            return CreateGeneratedFile(fileName, content);
        }

        public CodeBuilder CreateCodeBuilderPublic(string? version = null)
        {
            return CreateCodeBuilder(version);
        }
    }
}
