using System.Text;

namespace JD.Domain.T4.Shims;

/// <summary>
/// Simple code builder for T4 templates.
/// </summary>
public sealed class T4CodeBuilder
{
    private readonly StringBuilder _sb = new();
    private int _indent;
    private readonly string _indentString;

    /// <summary>
    /// Initializes a new instance of the <see cref="T4CodeBuilder"/> class.
    /// </summary>
    /// <param name="indentString">The string to use for indentation.</param>
    public T4CodeBuilder(string indentString = "    ")
    {
        _indentString = indentString;
    }

    /// <summary>
    /// Appends a line with the current indentation.
    /// </summary>
    /// <param name="line">The line to append.</param>
    /// <returns>This builder for chaining.</returns>
    public T4CodeBuilder AppendLine(string line = "")
    {
        if (string.IsNullOrEmpty(line))
        {
            _sb.AppendLine();
        }
        else
        {
            for (var i = 0; i < _indent; i++)
            {
                _sb.Append(_indentString);
            }
            _sb.AppendLine(line);
        }
        return this;
    }

    /// <summary>
    /// Increases the indentation level.
    /// </summary>
    /// <returns>This builder for chaining.</returns>
    public T4CodeBuilder Indent()
    {
        _indent++;
        return this;
    }

    /// <summary>
    /// Decreases the indentation level.
    /// </summary>
    /// <returns>This builder for chaining.</returns>
    public T4CodeBuilder Unindent()
    {
        if (_indent > 0) _indent--;
        return this;
    }

    /// <summary>
    /// Appends a block with braces.
    /// </summary>
    /// <param name="header">The block header.</param>
    /// <param name="content">Action to build content inside the block.</param>
    /// <returns>This builder for chaining.</returns>
    public T4CodeBuilder Block(string header, Action<T4CodeBuilder> content)
    {
        AppendLine(header);
        AppendLine("{");
        Indent();
        content(this);
        Unindent();
        AppendLine("}");
        return this;
    }

    /// <summary>
    /// Appends a namespace block.
    /// </summary>
    /// <param name="namespaceName">The namespace name.</param>
    /// <param name="content">Action to build content inside the namespace.</param>
    /// <returns>This builder for chaining.</returns>
    public T4CodeBuilder Namespace(string namespaceName, Action<T4CodeBuilder> content)
    {
        return Block($"namespace {namespaceName}", content);
    }

    /// <summary>
    /// Appends a class block.
    /// </summary>
    /// <param name="className">The class name.</param>
    /// <param name="modifiers">Class modifiers (e.g., "public partial").</param>
    /// <param name="baseClass">Optional base class.</param>
    /// <param name="content">Action to build content inside the class.</param>
    /// <returns>This builder for chaining.</returns>
    public T4CodeBuilder Class(string className, string modifiers, string? baseClass, Action<T4CodeBuilder> content)
    {
        var header = string.IsNullOrEmpty(baseClass)
            ? $"{modifiers} class {className}"
            : $"{modifiers} class {className} : {baseClass}";
        return Block(header, content);
    }

    /// <summary>
    /// Appends a property.
    /// </summary>
    /// <param name="type">The property type.</param>
    /// <param name="name">The property name.</param>
    /// <param name="accessors">The accessors (e.g., "get; set;").</param>
    /// <param name="modifiers">Optional modifiers.</param>
    /// <returns>This builder for chaining.</returns>
    public T4CodeBuilder Property(string type, string name, string accessors = "get; set;", string modifiers = "public")
    {
        return AppendLine($"{modifiers} {type} {name} {{ {accessors} }}");
    }

    /// <summary>
    /// Appends an auto-generated header comment.
    /// </summary>
    /// <param name="toolName">The name of the generating tool.</param>
    /// <returns>This builder for chaining.</returns>
    public T4CodeBuilder AutoGeneratedHeader(string toolName = "JD.Domain.T4")
    {
        AppendLine("// <auto-generated>");
        AppendLine($"// This code was generated by {toolName}.");
        AppendLine("// Changes to this file may be lost when the code is regenerated.");
        AppendLine("// </auto-generated>");
        AppendLine();
        return this;
    }

    /// <summary>
    /// Appends using statements.
    /// </summary>
    /// <param name="namespaces">The namespaces to use.</param>
    /// <returns>This builder for chaining.</returns>
    public T4CodeBuilder Usings(params string[] namespaces)
    {
        foreach (var ns in namespaces)
        {
            AppendLine($"using {ns};");
        }
        return this;
    }

    /// <summary>
    /// Returns the built code as a string.
    /// </summary>
    public override string ToString() => _sb.ToString();
}
