using System;
using System.Linq;
using JD.Domain.Abstractions;

namespace JD.Domain.T4.Shims;

/// <summary>
/// Generates entity code from manifests for T4 templates.
/// </summary>
public static class T4EntityGenerator
{
    /// <summary>
    /// Generates an entity class from a manifest.
    /// </summary>
    /// <param name="entity">The entity manifest.</param>
    /// <param name="namespace">The target namespace.</param>
    /// <param name="includeJdMarkers">Whether to include JD.Domain marker comments.</param>
    /// <returns>The generated code.</returns>
    public static string GenerateEntity(EntityManifest entity, string @namespace, bool includeJdMarkers = true)
    {
        if (entity == null) throw new ArgumentNullException(nameof(entity));

        var builder = new T4CodeBuilder();
        builder.AutoGeneratedHeader();
        builder.Usings("System", "System.Collections.Generic", "System.ComponentModel.DataAnnotations");
        builder.AppendLine();

        builder.Namespace(@namespace, b =>
        {
            if (includeJdMarkers)
            {
                b.AppendLine($"// [JD.Domain.Entity: {entity.Name}]");
            }

            b.AppendLine("/// <summary>");
            b.AppendLine($"/// Represents the {entity.Name} entity.");
            b.AppendLine("/// </summary>");
            b.Class(entity.Name, "public partial", null, c =>
            {
                // Generate properties
                foreach (var prop in entity.Properties.OrderBy(p => p.Name))
                {
                    var csharpType = T4TypeMapper.ToCSharpType(prop.TypeName);
                    if (!prop.IsRequired && !csharpType.EndsWith("?") && !T4TypeMapper.IsCollection(prop.TypeName))
                    {
                        csharpType += "?";
                    }

                    if (includeJdMarkers)
                    {
                        c.AppendLine($"// [JD.Domain.Property: {prop.Name}]");
                    }

                    // Add data annotations
                    if (entity.KeyProperties.Contains(prop.Name))
                    {
                        c.AppendLine("[Key]");
                    }
                    if (prop.IsRequired && csharpType == "string")
                    {
                        c.AppendLine("[Required]");
                    }
                    if (prop.MaxLength.HasValue)
                    {
                        c.AppendLine($"[MaxLength({prop.MaxLength.Value})]");
                    }

                    c.Property(csharpType, prop.Name);
                    c.AppendLine();
                }

                // Generate navigation properties placeholder
                c.AppendLine("// Navigation properties can be added in a partial class");
            });
        });

        return builder.ToString();
    }

    /// <summary>
    /// Generates an EF Core configuration class from a manifest.
    /// </summary>
    /// <param name="entity">The entity manifest.</param>
    /// <param name="config">Optional configuration manifest.</param>
    /// <param name="namespace">The target namespace.</param>
    /// <returns>The generated code.</returns>
    public static string GenerateConfiguration(EntityManifest entity, ConfigurationManifest? config, string @namespace)
    {
        if (entity == null) throw new ArgumentNullException(nameof(entity));

        var builder = new T4CodeBuilder();
        builder.AutoGeneratedHeader();
        builder.Usings(
            "Microsoft.EntityFrameworkCore",
            "Microsoft.EntityFrameworkCore.Metadata.Builders");
        builder.AppendLine();

        builder.Namespace(@namespace, b =>
        {
            b.AppendLine("/// <summary>");
            b.AppendLine($"/// EF Core configuration for {entity.Name}.");
            b.AppendLine("/// </summary>");
            b.Class($"{entity.Name}Configuration", "public partial", $"IEntityTypeConfiguration<{entity.Name}>", c =>
            {
                c.AppendLine("/// <inheritdoc/>");
                c.Block($"public void Configure(EntityTypeBuilder<{entity.Name}> builder)", m =>
                {
                    // Table name
                    var tableName = config?.TableName ?? entity.TableName ?? entity.Name + "s";
                    var schemaName = config?.SchemaName ?? entity.SchemaName;
                    if (!string.IsNullOrEmpty(schemaName))
                    {
                        m.AppendLine($"builder.ToTable(\"{tableName}\", \"{schemaName}\");");
                    }
                    else
                    {
                        m.AppendLine($"builder.ToTable(\"{tableName}\");");
                    }
                    m.AppendLine();

                    // Primary key
                    if (entity.KeyProperties.Count == 1)
                    {
                        m.AppendLine($"builder.HasKey(e => e.{entity.KeyProperties[0]});");
                    }
                    else if (entity.KeyProperties.Count > 1)
                    {
                        var keys = string.Join(", ", entity.KeyProperties.Select(k => $"e.{k}"));
                        m.AppendLine($"builder.HasKey(e => new {{ {keys} }});");
                    }
                    m.AppendLine();

                    // Property configurations
                    m.AppendLine("// Property configurations");
                    foreach (var prop in entity.Properties.OrderBy(p => p.Name))
                    {
                        PropertyConfigurationManifest? propConfig = null;
                        config?.PropertyConfigurations.TryGetValue(prop.Name, out propConfig);
                        var hasConfig = prop.IsRequired || prop.MaxLength.HasValue || propConfig != null;

                        if (!hasConfig) continue;

                        m.AppendLine($"builder.Property(e => e.{prop.Name})");
                        m.Indent();

                        if (prop.IsRequired)
                        {
                            m.AppendLine(".IsRequired()");
                        }
                        if (prop.MaxLength.HasValue)
                        {
                            m.AppendLine($".HasMaxLength({prop.MaxLength.Value})");
                        }
                        if (propConfig?.ColumnName != null)
                        {
                            m.AppendLine($".HasColumnName(\"{propConfig.ColumnName}\")");
                        }

                        m.Unindent();
                        m.AppendLine(";");
                        m.AppendLine();
                    }

                    m.AppendLine("// Additional configuration can be added in a partial class");
                });
            });
        });

        return builder.ToString();
    }

    /// <summary>
    /// Generates a JD.Domain rules partial class for an entity.
    /// </summary>
    /// <param name="entity">The entity manifest.</param>
    /// <param name="ruleSets">The rule sets for this entity.</param>
    /// <param name="namespace">The target namespace.</param>
    /// <returns>The generated code.</returns>
    public static string GenerateRulesPartial(EntityManifest entity, RuleSetManifest[] ruleSets, string @namespace)
    {
        if (entity == null) throw new ArgumentNullException(nameof(entity));

        var builder = new T4CodeBuilder();
        builder.AutoGeneratedHeader();
        builder.Usings("JD.Domain.Rules");
        builder.AppendLine();

        builder.Namespace(@namespace, b =>
        {
            b.AppendLine("/// <summary>");
            b.AppendLine($"/// JD.Domain rules for {entity.Name}.");
            b.AppendLine("/// </summary>");
            b.Class($"{entity.Name}Rules", "public static partial", null, c =>
            {
                foreach (var ruleSet in ruleSets)
                {
                    c.AppendLine($"// Rule set: {ruleSet.Name}");
                    foreach (var rule in ruleSet.Rules)
                    {
                        c.AppendLine($"// - {rule.Id}: {rule.Message ?? "(no message)"}");
                    }
                    c.AppendLine();
                }

                c.AppendLine("// Implement rules using JD.Domain.Rules DSL");
                c.AppendLine("// Example:");
                c.AppendLine("// public static RuleSet<" + entity.Name + "> Default => RuleSet.For<" + entity.Name + ">(\"Default\")");
                c.AppendLine("//     .Invariant(x => !string.IsNullOrEmpty(x.Name), \"Name is required\");");
            });
        });

        return builder.ToString();
    }
}
