using System.Collections.Generic;
using System.Threading;

namespace JD.Domain.Generators.Core;

/// <summary>
/// Base class for code generators providing common functionality.
/// </summary>
public abstract class BaseCodeGenerator : ICodeGenerator
{
    /// <summary>
    /// Gets the name of this generator.
    /// </summary>
    public abstract string Name { get; }

    /// <summary>
    /// Generates code files from the given context.
    /// </summary>
    public abstract IEnumerable<GeneratedFile> Generate(GeneratorContext context, CancellationToken cancellationToken = default);

    /// <summary>
    /// Determines if this generator can process the given manifest.
    /// Default implementation returns true if manifest is not null.
    /// </summary>
    public virtual bool CanGenerate(GeneratorContext context)
    {
        return context?.Manifest != null;
    }

    /// <summary>
    /// Creates a generated file with computed hash.
    /// </summary>
    protected GeneratedFile CreateGeneratedFile(string fileName, string content)
    {
        var normalizedContent = GeneratorUtilities.NormalizeLineEndings(content);
        var hash = GeneratorUtilities.ComputeHash(normalizedContent);

        return new GeneratedFile
        {
            FileName = fileName,
            Content = normalizedContent,
            ContentHash = hash
        };
    }

    /// <summary>
    /// Creates a code builder with standard auto-generated header.
    /// </summary>
    protected CodeBuilder CreateCodeBuilder(string? version = null)
    {
        var builder = new CodeBuilder();
        builder.AutoGeneratedHeader(Name, version);
        return builder;
    }
}
