using System.Text;

namespace JD.Domain.Generators.Core;

/// <summary>
/// Fluent builder for generating C# code with proper formatting and indentation.
/// </summary>
public sealed class CodeBuilder
{
    private readonly StringBuilder _builder = new();
    private int _indentLevel;
    private bool _needsIndent = true;
    private readonly string _indentString;

    /// <summary>
    /// Initializes a new instance of the <see cref="CodeBuilder"/> class.
    /// </summary>
    /// <param name="indentString">The string to use for indentation (default is 4 spaces).</param>
    public CodeBuilder(string indentString = "    ")
    {
        _indentString = indentString;
    }

    /// <summary>
    /// Appends a line of code with current indentation.
    /// </summary>
    public CodeBuilder AppendLine(string? line = null)
    {
        if (line != null)
        {
            if (_needsIndent)
            {
                for (int i = 0; i < _indentLevel; i++)
                {
                    _builder.Append(_indentString);
                }
                _needsIndent = false;
            }
            _builder.Append(line);
        }
        _builder.AppendLine();
        _needsIndent = true;
        return this;
    }

    /// <summary>
    /// Appends text without a newline.
    /// </summary>
    public CodeBuilder Append(string text)
    {
        if (_needsIndent)
        {
            for (int i = 0; i < _indentLevel; i++)
            {
                _builder.Append(_indentString);
            }
            _needsIndent = false;
        }
        _builder.Append(text);
        return this;
    }

    /// <summary>
    /// Increases the indentation level.
    /// </summary>
    public CodeBuilder Indent()
    {
        _indentLevel++;
        return this;
    }

    /// <summary>
    /// Decreases the indentation level.
    /// </summary>
    public CodeBuilder Unindent()
    {
        if (_indentLevel > 0)
        {
            _indentLevel--;
        }
        return this;
    }

    /// <summary>
    /// Appends an opening brace and increases indentation.
    /// </summary>
    public CodeBuilder OpenBrace()
    {
        AppendLine("{");
        Indent();
        return this;
    }

    /// <summary>
    /// Decreases indentation and appends a closing brace.
    /// </summary>
    public CodeBuilder CloseBrace()
    {
        Unindent();
        AppendLine("}");
        return this;
    }

    /// <summary>
    /// Appends a using directive.
    /// </summary>
    public CodeBuilder Using(string namespaceName)
    {
        AppendLine($"using {namespaceName};");
        return this;
    }

    /// <summary>
    /// Appends multiple using directives in sorted order.
    /// </summary>
    public CodeBuilder Usings(params string[] namespaces)
    {
        var sorted = new List<string>(namespaces);
        sorted.Sort();
        foreach (var ns in sorted)
        {
            Using(ns);
        }
        return this;
    }

    /// <summary>
    /// Begins a namespace block.
    /// </summary>
    public CodeBuilder BeginNamespace(string namespaceName)
    {
        AppendLine($"namespace {namespaceName}");
        OpenBrace();
        return this;
    }

    /// <summary>
    /// Ends a namespace block.
    /// </summary>
    public CodeBuilder EndNamespace()
    {
        CloseBrace();
        return this;
    }

    /// <summary>
    /// Begins a class declaration.
    /// </summary>
    public CodeBuilder BeginClass(string className, string? accessibility = "public", string? modifiers = null, string? baseType = null)
    {
        var line = accessibility != null ? $"{accessibility} " : "";
        if (modifiers != null)
        {
            line += $"{modifiers} ";
        }
        line += $"class {className}";
        if (baseType != null)
        {
            line += $" : {baseType}";
        }
        AppendLine(line);
        OpenBrace();
        return this;
    }

    /// <summary>
    /// Ends a class declaration.
    /// </summary>
    public CodeBuilder EndClass()
    {
        CloseBrace();
        return this;
    }

    /// <summary>
    /// Appends the auto-generated file header.
    /// </summary>
    public CodeBuilder AutoGeneratedHeader(
        string generatorName,
        string? version = null,
        DateTimeOffset? generatedAt = null)
    {
        var timestamp = generatedAt ??
            new DateTimeOffset(1970, 1, 1, 0, 0, 0, TimeSpan.Zero);
        AppendLine("// <auto-generated>");
        AppendLine($"// Generated by {generatorName}");
        if (version != null)
        {
            AppendLine($"// Version: {version}");
        }
        AppendLine($"// Generated at: {timestamp:O}");
        AppendLine("// </auto-generated>");
        AppendLine();
        AppendLine("#nullable enable");
        AppendLine();
        return this;
    }

    /// <summary>
    /// Returns the built code as a string.
    /// </summary>
    public override string ToString()
    {
        return _builder.ToString();
    }
}
