using JD.Domain.Abstractions;
using JD.Domain.T4.Shims;

namespace JD.Domain.Tests.Unit.T4Shims;

public class T4ShimsTests
{
    [Theory]
    [InlineData("System.String", "string")]
    [InlineData("System.Int32", "int")]
    [InlineData("System.Boolean", "bool")]
    [InlineData("System.Guid", "Guid")]
    [InlineData("System.DateTime", "DateTime")]
    [InlineData("System.String?", "string?")]
    [InlineData("System.Int32?", "int?")]
    [InlineData("MyNamespace.MyClass", "MyClass")]
    public void T4TypeMapper_ToCSharpType_MapsCorrectly(string clrType, string expected)
    {
        var result = T4TypeMapper.ToCSharpType(clrType);
        Assert.Equal(expected, result);
    }

    [Theory]
    [InlineData("System.String", null, "nvarchar(max)")]
    [InlineData("System.String", 100, "nvarchar(100)")]
    [InlineData("System.Int32", null, "int")]
    [InlineData("System.Boolean", null, "bit")]
    [InlineData("System.Guid", null, "uniqueidentifier")]
    [InlineData("System.DateTime", null, "datetime2")]
    public void T4TypeMapper_ToSqlServerType_MapsCorrectly(string clrType, int? maxLength, string expected)
    {
        var result = T4TypeMapper.ToSqlServerType(clrType, maxLength);
        Assert.Equal(expected, result);
    }

    [Theory]
    [InlineData("System.String", true)]
    [InlineData("System.Int32", true)]
    [InlineData("System.Guid", true)]
    [InlineData("MyNamespace.MyClass", false)]
    [InlineData("System.Collections.Generic.List`1[System.String]", false)]
    public void T4TypeMapper_IsPrimitiveOrSimple_ClassifiesCorrectly(string clrType, bool expected)
    {
        var result = T4TypeMapper.IsPrimitiveOrSimple(clrType);
        Assert.Equal(expected, result);
    }

    [Theory]
    [InlineData("System.Collections.Generic.ICollection`1[System.String]", true)]
    [InlineData("System.Collections.Generic.List`1[System.Int32]", true)]
    [InlineData("System.String[]", true)]
    [InlineData("System.String", false)]
    public void T4TypeMapper_IsCollection_ClassifiesCorrectly(string clrType, bool expected)
    {
        var result = T4TypeMapper.IsCollection(clrType);
        Assert.Equal(expected, result);
    }

    [Fact]
    public void T4CodeBuilder_Block_GeneratesCorrectStructure()
    {
        var builder = new T4CodeBuilder();
        builder.Block("public class Test", b =>
        {
            b.Property("string", "Name");
        });

        var result = builder.ToString();

        Assert.Contains("public class Test", result);
        Assert.Contains("{", result);
        Assert.Contains("}", result);
        Assert.Contains("public string Name { get; set; }", result);
    }

    [Fact]
    public void T4CodeBuilder_Namespace_GeneratesCorrectStructure()
    {
        var builder = new T4CodeBuilder();
        builder.Namespace("MyNamespace", b =>
        {
            b.AppendLine("// Content");
        });

        var result = builder.ToString();

        Assert.Contains("namespace MyNamespace", result);
        Assert.Contains("// Content", result);
    }

    [Fact]
    public void T4CodeBuilder_AutoGeneratedHeader_IncludesMarkers()
    {
        var builder = new T4CodeBuilder();
        builder.AutoGeneratedHeader("TestTool");

        var result = builder.ToString();

        Assert.Contains("<auto-generated>", result);
        Assert.Contains("TestTool", result);
        Assert.Contains("</auto-generated>", result);
    }

    [Fact]
    public void T4EntityGenerator_GenerateEntity_IncludesProperties()
    {
        var entity = new EntityManifest
        {
            Name = "Customer",
            TypeName = "TestDomain.Customer",
            Properties =
            [
                new PropertyManifest { Name = "Id", TypeName = "System.Guid", IsRequired = true },
                new PropertyManifest { Name = "Name", TypeName = "System.String", IsRequired = true, MaxLength = 100 },
                new PropertyManifest { Name = "Email", TypeName = "System.String", IsRequired = false }
            ],
            KeyProperties = ["Id"]
        };

        var code = T4EntityGenerator.GenerateEntity(entity, "TestNamespace");

        Assert.Contains("namespace TestNamespace", code);
        Assert.Contains("public partial class Customer", code);
        Assert.Contains("[Key]", code);
        Assert.Contains("public Guid Id { get; set; }", code);
        Assert.Contains("[Required]", code);
        Assert.Contains("[MaxLength(100)]", code);
        Assert.Contains("public string Name { get; set; }", code);
        Assert.Contains("public string? Email { get; set; }", code);
    }

    [Fact]
    public void T4EntityGenerator_GenerateEntity_WithJdMarkers_IncludesMarkers()
    {
        var entity = new EntityManifest
        {
            Name = "Order",
            TypeName = "TestDomain.Order",
            Properties =
            [
                new PropertyManifest { Name = "Id", TypeName = "System.Int32", IsRequired = true }
            ],
            KeyProperties = ["Id"]
        };

        var code = T4EntityGenerator.GenerateEntity(entity, "TestNamespace", includeJdMarkers: true);

        Assert.Contains("[JD.Domain.Entity: Order]", code);
        Assert.Contains("[JD.Domain.Property: Id]", code);
    }

    [Fact]
    public void T4EntityGenerator_GenerateConfiguration_IncludesTableAndKey()
    {
        var entity = new EntityManifest
        {
            Name = "Product",
            TypeName = "TestDomain.Product",
            TableName = "Products",
            Properties =
            [
                new PropertyManifest { Name = "Id", TypeName = "System.Guid", IsRequired = true },
                new PropertyManifest { Name = "Name", TypeName = "System.String", IsRequired = true, MaxLength = 200 }
            ],
            KeyProperties = ["Id"]
        };

        var code = T4EntityGenerator.GenerateConfiguration(entity, null, "TestNamespace");

        Assert.Contains("IEntityTypeConfiguration<Product>", code);
        Assert.Contains("builder.ToTable(\"Products\")", code);
        Assert.Contains("builder.HasKey(e => e.Id)", code);
        Assert.Contains(".IsRequired()", code);
        Assert.Contains(".HasMaxLength(200)", code);
    }

    [Fact]
    public void T4EntityGenerator_GenerateConfiguration_WithSchema_IncludesSchema()
    {
        var entity = new EntityManifest
        {
            Name = "Order",
            TypeName = "TestDomain.Order",
            TableName = "Orders",
            SchemaName = "sales",
            Properties = [new PropertyManifest { Name = "Id", TypeName = "System.Int32", IsRequired = true }],
            KeyProperties = ["Id"]
        };

        var code = T4EntityGenerator.GenerateConfiguration(entity, null, "TestNamespace");

        Assert.Contains("builder.ToTable(\"Orders\", \"sales\")", code);
    }

    [Fact]
    public void T4EntityGenerator_GenerateRulesPartial_IncludesRuleSetInfo()
    {
        var entity = new EntityManifest
        {
            Name = "Customer",
            TypeName = "TestDomain.Customer",
            KeyProperties = ["Id"]
        };

        var ruleSets = new[]
        {
            new RuleSetManifest
            {
                Name = "Default",
                TargetType = "TestDomain.Customer",
                Rules =
                [
                    new RuleManifest
                    {
                        Id = "Customer.Name.Required",
                        Category = "Invariant",
                        TargetType = "TestDomain.Customer",
                        Message = "Name is required"
                    }
                ]
            }
        };

        var code = T4EntityGenerator.GenerateRulesPartial(entity, ruleSets, "TestNamespace");

        Assert.Contains("public static partial class CustomerRules", code);
        Assert.Contains("Rule set: Default", code);
        Assert.Contains("Customer.Name.Required", code);
        Assert.Contains("Name is required", code);
    }
}
