using JD.Domain.Abstractions;
using JD.Domain.Snapshot;
using JD.Domain.T4.Shims;

namespace JD.Domain.Tests.Unit.T4Shims;

public class T4ShimsTests
{
    [Theory]
    [InlineData("System.String", "string")]
    [InlineData("System.Int32", "int")]
    [InlineData("System.Boolean", "bool")]
    [InlineData("System.Guid", "Guid")]
    [InlineData("System.DateTime", "DateTime")]
    [InlineData("System.String?", "string?")]
    [InlineData("System.Int32?", "int?")]
    [InlineData("MyNamespace.MyClass", "MyClass")]
    public void T4TypeMapper_ToCSharpType_MapsCorrectly(string clrType, string expected)
    {
        var result = T4TypeMapper.ToCSharpType(clrType);
        Assert.Equal(expected, result);
    }

    [Fact]
    public void T4TypeMapper_ToCSharpType_ReturnsEmptyForEmptyString()
    {
        Assert.Equal(string.Empty, T4TypeMapper.ToCSharpType(string.Empty));
    }

    [Fact]
    public void T4TypeMapper_ToCSharpType_HandlesNullableGenericSyntax()
    {
        var result = T4TypeMapper.ToCSharpType("System.Nullable`1[System.Int32]");
        Assert.Equal("int?", result);
    }

    [Theory]
    [InlineData("System.String", null, "nvarchar(max)")]
    [InlineData("System.String", 100, "nvarchar(100)")]
    [InlineData("System.Int32", null, "int")]
    [InlineData("System.Boolean", null, "bit")]
    [InlineData("System.Guid", null, "uniqueidentifier")]
    [InlineData("System.DateTime", null, "datetime2")]
    public void T4TypeMapper_ToSqlServerType_MapsCorrectly(string clrType, int? maxLength, string expected)
    {
        var result = T4TypeMapper.ToSqlServerType(clrType, maxLength);
        Assert.Equal(expected, result);
    }

    [Fact]
    public void T4TypeMapper_ToSqlServerType_DefaultsForUnknown()
    {
        var result = T4TypeMapper.ToSqlServerType(null!);
        Assert.Equal("nvarchar(max)", result);
    }

    [Fact]
    public void T4TypeMapper_ToSqlServerType_ReturnsDefaultForUnknownType()
    {
        var result = T4TypeMapper.ToSqlServerType("Custom.Type");
        Assert.Equal("nvarchar(max)", result);
    }

    [Theory]
    [InlineData("System.String", true)]
    [InlineData("System.Int32", true)]
    [InlineData("System.Guid", true)]
    [InlineData("MyNamespace.MyClass", false)]
    [InlineData("System.Collections.Generic.List`1[System.String]", false)]
    public void T4TypeMapper_IsPrimitiveOrSimple_ClassifiesCorrectly(string clrType, bool expected)
    {
        var result = T4TypeMapper.IsPrimitiveOrSimple(clrType);
        Assert.Equal(expected, result);
    }

    [Fact]
    public void T4TypeMapper_IsPrimitiveOrSimple_ReturnsFalseForNull()
    {
        Assert.False(T4TypeMapper.IsPrimitiveOrSimple(null!));
    }

    [Theory]
    [InlineData("System.Collections.Generic.ICollection`1[System.String]", true)]
    [InlineData("System.Collections.Generic.List`1[System.Int32]", true)]
    [InlineData("System.String[]", true)]
    [InlineData("System.String", false)]
    public void T4TypeMapper_IsCollection_ClassifiesCorrectly(string clrType, bool expected)
    {
        var result = T4TypeMapper.IsCollection(clrType);
        Assert.Equal(expected, result);
    }

    [Fact]
    public void T4TypeMapper_IsCollection_DetectsHashSet()
    {
        Assert.True(T4TypeMapper.IsCollection("System.Collections.Generic.HashSet`1[System.Int32]"));
    }

    [Fact]
    public void T4TypeMapper_IsCollection_ReturnsFalseForEmpty()
    {
        Assert.False(T4TypeMapper.IsCollection(string.Empty));
    }

    [Fact]
    public void T4CodeBuilder_Block_GeneratesCorrectStructure()
    {
        var builder = new T4CodeBuilder();
        builder.Block("public class Test", b =>
        {
            b.Property("string", "Name");
        });

        var result = builder.ToString();

        Assert.Contains("public class Test", result);
        Assert.Contains("{", result);
        Assert.Contains("}", result);
        Assert.Contains("public string Name { get; set; }", result);
    }

    [Fact]
    public void T4CodeBuilder_Namespace_GeneratesCorrectStructure()
    {
        var builder = new T4CodeBuilder();
        builder.Namespace("MyNamespace", b =>
        {
            b.AppendLine("// Content");
        });

        var result = builder.ToString();

        Assert.Contains("namespace MyNamespace", result);
        Assert.Contains("// Content", result);
    }

    [Fact]
    public void T4CodeBuilder_AutoGeneratedHeader_IncludesMarkers()
    {
        var builder = new T4CodeBuilder();
        builder.AutoGeneratedHeader("TestTool");

        var result = builder.ToString();

        Assert.Contains("<auto-generated>", result);
        Assert.Contains("TestTool", result);
        Assert.Contains("</auto-generated>", result);
    }

    [Fact]
    public void T4EntityGenerator_GenerateEntity_IncludesProperties()
    {
        var entity = new EntityManifest
        {
            Name = "Customer",
            TypeName = "TestDomain.Customer",
            Properties =
            [
                new PropertyManifest { Name = "Id", TypeName = "System.Guid", IsRequired = true },
                new PropertyManifest { Name = "Name", TypeName = "System.String", IsRequired = true, MaxLength = 100 },
                new PropertyManifest { Name = "Email", TypeName = "System.String", IsRequired = false }
            ],
            KeyProperties = ["Id"]
        };

        var code = T4EntityGenerator.GenerateEntity(entity, "TestNamespace");

        Assert.Contains("namespace TestNamespace", code);
        Assert.Contains("public partial class Customer", code);
        Assert.Contains("[Key]", code);
        Assert.Contains("public Guid Id { get; set; }", code);
        Assert.Contains("[Required]", code);
        Assert.Contains("[MaxLength(100)]", code);
        Assert.Contains("public string Name { get; set; }", code);
        Assert.Contains("public string? Email { get; set; }", code);
    }

    [Fact]
    public void T4EntityGenerator_GenerateEntity_WithJdMarkers_IncludesMarkers()
    {
        var entity = new EntityManifest
        {
            Name = "Order",
            TypeName = "TestDomain.Order",
            Properties =
            [
                new PropertyManifest { Name = "Id", TypeName = "System.Int32", IsRequired = true }
            ],
            KeyProperties = ["Id"]
        };

        var code = T4EntityGenerator.GenerateEntity(entity, "TestNamespace", includeJdMarkers: true);

        Assert.Contains("[JD.Domain.Entity: Order]", code);
        Assert.Contains("[JD.Domain.Property: Id]", code);
    }

    [Fact]
    public void T4EntityGenerator_GenerateConfiguration_IncludesTableAndKey()
    {
        var entity = new EntityManifest
        {
            Name = "Product",
            TypeName = "TestDomain.Product",
            TableName = "Products",
            Properties =
            [
                new PropertyManifest { Name = "Id", TypeName = "System.Guid", IsRequired = true },
                new PropertyManifest { Name = "Name", TypeName = "System.String", IsRequired = true, MaxLength = 200 }
            ],
            KeyProperties = ["Id"]
        };

        var code = T4EntityGenerator.GenerateConfiguration(entity, null, "TestNamespace");

        Assert.Contains("IEntityTypeConfiguration<Product>", code);
        Assert.Contains("builder.ToTable(\"Products\")", code);
        Assert.Contains("builder.HasKey(e => e.Id)", code);
        Assert.Contains(".IsRequired()", code);
        Assert.Contains(".HasMaxLength(200)", code);
    }

    [Fact]
    public void T4EntityGenerator_GenerateConfiguration_WithSchema_IncludesSchema()
    {
        var entity = new EntityManifest
        {
            Name = "Order",
            TypeName = "TestDomain.Order",
            TableName = "Orders",
            SchemaName = "sales",
            Properties = [new PropertyManifest { Name = "Id", TypeName = "System.Int32", IsRequired = true }],
            KeyProperties = ["Id"]
        };

        var code = T4EntityGenerator.GenerateConfiguration(entity, null, "TestNamespace");

        Assert.Contains("builder.ToTable(\"Orders\", \"sales\")", code);
    }

    [Fact]
    public void T4EntityGenerator_GenerateConfiguration_WithCompositeKey_UsesAnonymousKey()
    {
        var entity = new EntityManifest
        {
            Name = "Product",
            TypeName = "TestDomain.Product",
            Properties =
            [
                new PropertyManifest { Name = "Id", TypeName = "System.Guid", IsRequired = true },
                new PropertyManifest { Name = "TenantId", TypeName = "System.Guid", IsRequired = true },
                new PropertyManifest { Name = "Name", TypeName = "System.String", IsRequired = true }
            ],
            KeyProperties = ["Id", "TenantId"]
        };

        var config = new ConfigurationManifest
        {
            EntityName = "Product",
            EntityTypeName = "TestDomain.Product",
            PropertyConfigurations = new Dictionary<string, PropertyConfigurationManifest>
            {
                ["Name"] = new PropertyConfigurationManifest
                {
                    PropertyName = "Name",
                    ColumnName = "product_name"
                }
            }
        };

        var code = T4EntityGenerator.GenerateConfiguration(entity, config, "TestNamespace");

        Assert.Contains("builder.HasKey(e => new { e.Id, e.TenantId })", code);
        Assert.Contains(".HasColumnName(\"product_name\")", code);
    }

    [Fact]
    public void T4EntityGenerator_GenerateRulesPartial_IncludesRuleSetInfo()
    {
        var entity = new EntityManifest
        {
            Name = "Customer",
            TypeName = "TestDomain.Customer",
            KeyProperties = ["Id"]
        };

        var ruleSets = new[]
        {
            new RuleSetManifest
            {
                Name = "Default",
                TargetType = "TestDomain.Customer",
                Rules =
                [
                    new RuleManifest
                    {
                        Id = "Customer.Name.Required",
                        Category = "Invariant",
                        TargetType = "TestDomain.Customer",
                        Message = "Name is required"
                    }
                ]
            }
        };

        var code = T4EntityGenerator.GenerateRulesPartial(entity, ruleSets, "TestNamespace");

        Assert.Contains("public static partial class CustomerRules", code);
        Assert.Contains("Rule set: Default", code);
        Assert.Contains("Customer.Name.Required", code);
        Assert.Contains("Name is required", code);
    }

    [Fact]
    public void T4OutputManager_WritesFilesAndCleansDirectory()
    {
        var tempDir = Path.Combine(Path.GetTempPath(), $"JD.Domain.Tests.{Guid.NewGuid()}");
        Directory.CreateDirectory(tempDir);
        var staleFile = Path.Combine(tempDir, "stale.cs");
        File.WriteAllText(staleFile, "// stale");

        try
        {
            var manager = new T4OutputManager(tempDir);
            manager.AddFile("Generated/One.cs", "// one");
            manager.AddFile("Two.cs", "// two");

            manager.WriteAll(cleanDirectory: true);

            Assert.False(File.Exists(staleFile));
            Assert.True(File.Exists(Path.Combine(tempDir, "Generated", "One.cs")));
            Assert.True(File.Exists(Path.Combine(tempDir, "Two.cs")));
            Assert.Equal(new[] { "Generated/One.cs", "Two.cs" }, manager.GetFileNames());
        }
        finally
        {
            if (Directory.Exists(tempDir))
            {
                Directory.Delete(tempDir, true);
            }
        }
    }

    [Fact]
    public void T4OutputManager_WriteAll_CreatesDirectory_WhenMissing()
    {
        var tempDir = Path.Combine(Path.GetTempPath(), $"JD.Domain.Tests.{Guid.NewGuid()}");

        try
        {
            var manager = new T4OutputManager(tempDir);
            manager.AddFile("One.cs", "// one");

            manager.WriteAll();

            Assert.True(Directory.Exists(tempDir));
            Assert.True(File.Exists(Path.Combine(tempDir, "One.cs")));
        }
        finally
        {
            if (Directory.Exists(tempDir))
            {
                Directory.Delete(tempDir, true);
            }
        }
    }

    [Fact]
    public void T4OutputManager_Clear_RemovesPendingFiles()
    {
        var tempDir = Path.Combine(Path.GetTempPath(), $"JD.Domain.Tests.{Guid.NewGuid()}");
        Directory.CreateDirectory(tempDir);

        try
        {
            var manager = new T4OutputManager(tempDir);
            manager.AddFile("One.cs", "// one");
            manager.Clear();

            Assert.Empty(manager.GetFileNames());
        }
        finally
        {
            if (Directory.Exists(tempDir))
            {
                Directory.Delete(tempDir, true);
            }
        }
    }

    [Fact]
    public void T4ManifestLoader_LoadsManifestAndSnapshot()
    {
        var tempDir = Path.Combine(Path.GetTempPath(), $"JD.Domain.Tests.{Guid.NewGuid()}");
        Directory.CreateDirectory(tempDir);

        try
        {
            var manifest = new DomainManifest
            {
                Name = "TestDomain",
                Version = new Version(1, 0, 0)
            };
            var writer = new SnapshotWriter();

            var manifestPath = Path.Combine(tempDir, "manifest.json");
            File.WriteAllText(manifestPath, writer.SerializeManifest(manifest));

            var snapshot = writer.CreateSnapshot(manifest);
            var snapshotPath = Path.Combine(tempDir, "snapshot.json");
            File.WriteAllText(snapshotPath, writer.Serialize(snapshot));

            var loadedManifest = T4ManifestLoader.LoadManifest(manifestPath);
            var loadedSnapshot = T4ManifestLoader.LoadSnapshot(snapshotPath);

            Assert.Equal("TestDomain", loadedManifest.Name);
            Assert.Equal("TestDomain", loadedSnapshot.Name);
        }
        finally
        {
            if (Directory.Exists(tempDir))
            {
                Directory.Delete(tempDir, true);
            }
        }
    }

    [Fact]
    public void T4ManifestLoader_TryLoadManifest_ReturnsNullForMissingFile()
    {
        var result = T4ManifestLoader.TryLoadManifest(Path.Combine(Path.GetTempPath(), Guid.NewGuid().ToString(), "missing.json"));

        Assert.Null(result);
    }

    [Fact]
    public void T4ManifestLoader_LoadManifest_ThrowsOnInvalidPath()
    {
        Assert.Throws<ArgumentException>(() => T4ManifestLoader.LoadManifest(string.Empty));
    }

    [Fact]
    public void T4ManifestLoader_LoadSnapshot_ThrowsOnMissingFile()
    {
        var missingPath = Path.Combine(Path.GetTempPath(), Guid.NewGuid().ToString(), "missing.json");

        Assert.Throws<FileNotFoundException>(() => T4ManifestLoader.LoadSnapshot(missingPath));
    }

    [Fact]
    public void T4ManifestLoader_LoadSnapshot_ThrowsOnEmptyPath()
    {
        Assert.Throws<ArgumentException>(() => T4ManifestLoader.LoadSnapshot(string.Empty));
    }
}
