using System;
using System.Collections.Generic;
using System.Linq;
using JD.Domain.Abstractions;
using JD.Domain.FluentValidation.Generator;
using JD.Domain.Generators.Core;
using JD.Domain.Rules;
using Xunit;
using Domain = JD.Domain.Modeling.Domain;

namespace JD.Domain.Tests.Unit.FluentValidation;

public class FluentValidationGeneratorTests
{
    private class TestEntity
    {
        public int Id { get; set; }
        public string Name { get; set; } = string.Empty;
        public int Count { get; set; }
    }

    private static GeneratorContext CreateContext(DomainManifest manifest, Dictionary<string, string>? properties = null)
    {
        var compilation = Microsoft.CodeAnalysis.CSharp.CSharpCompilation.Create("Test");
        return new GeneratorContext
        {
            Manifest = manifest,
            Compilation = compilation,
            CancellationToken = System.Threading.CancellationToken.None,
            Properties = properties ?? new Dictionary<string, string>()
        };
    }

    [Fact]
    public void Generator_HasCorrectName()
    {
        var generator = new FluentValidationGenerator();
        Assert.Equal("FluentValidationGenerator", generator.Name);
    }

    [Fact]
    public void CanGenerate_ReturnsFalse_WhenNoRuleSets()
    {
        var manifest = JD.Domain.Modeling.Domain.Create("Test")
            .Version(1, 0, 0)
            .BuildManifest();

        var context = CreateContext(manifest);
        var generator = new FluentValidationGenerator();

        Assert.False(generator.CanGenerate(context));
    }

    [Fact]
    public void CanGenerate_ReturnsTrue_WhenRuleSetsExist()
    {
        var manifest = JD.Domain.Modeling.Domain.Create("Test")
            .Version(1, 0, 0)
            .Entity<TestEntity>()
            .Rules<TestEntity>(r => r
                .Invariant("TestRule", x => x.Name.Length > 0))
            .BuildManifest();

        var context = CreateContext(manifest);
        var generator = new FluentValidationGenerator();

        Assert.True(generator.CanGenerate(context));
    }

    [Fact]
    public void Generate_CreatesValidatorFile()
    {
        var manifest = JD.Domain.Modeling.Domain.Create("TestDomain")
            .Version(1, 0, 0)
            .Entity<TestEntity>()
            .Rules<TestEntity>(r => r
                .Invariant("NameRequired", x => !string.IsNullOrWhiteSpace(x.Name))
                    .WithMessage("Name is required")
                    .WithSeverity(RuleSeverity.Error))
            .BuildManifest();

        var context = CreateContext(manifest);
        var generator = new FluentValidationGenerator();
        var files = generator.Generate(context).ToList();

        Assert.Single(files);
        var file = files[0];
        Assert.Equal("TestEntityDefaultValidator.g.cs", file.FileName);
        Assert.NotEmpty(file.Content);
    }

    [Fact]
    public void Generate_IncludesAutoGeneratedHeader()
    {
        var manifest = JD.Domain.Modeling.Domain.Create("TestDomain")
            .Version(1, 0, 0)
            .Entity<TestEntity>()
            .Rules<TestEntity>(r => r
                .Invariant("NameRequired", x => !string.IsNullOrWhiteSpace(x.Name)))
            .BuildManifest();

        var context = CreateContext(manifest);
        var generator = new FluentValidationGenerator();
        var files = generator.Generate(context).ToList();

        var content = files[0].Content;
        Assert.Contains("// <auto-generated>", content);
        Assert.Contains("FluentValidationGenerator", content);
    }

    [Fact]
    public void Generate_IncludesRequiredUsings()
    {
        var manifest = JD.Domain.Modeling.Domain.Create("TestDomain")
            .Version(1, 0, 0)
            .Entity<TestEntity>()
            .Rules<TestEntity>(r => r
                .Invariant("NameRequired", x => !string.IsNullOrWhiteSpace(x.Name)))
            .BuildManifest();

        var context = CreateContext(manifest);
        var generator = new FluentValidationGenerator();
        var files = generator.Generate(context).ToList();

        var content = files[0].Content;
        Assert.Contains("using System;", content);
        Assert.Contains("using FluentValidation;", content);
        Assert.Contains("using JD.Domain.Abstractions;", content);
    }

    [Fact]
    public void Generate_CreatesValidatorClass()
    {
        var manifest = JD.Domain.Modeling.Domain.Create("TestDomain")
            .Version(1, 0, 0)
            .Entity<TestEntity>()
            .Rules<TestEntity>(r => r
                .Invariant("NameRequired", x => !string.IsNullOrWhiteSpace(x.Name)))
            .BuildManifest();

        var context = CreateContext(manifest);
        var generator = new FluentValidationGenerator();
        var files = generator.Generate(context).ToList();

        var content = files[0].Content;
        Assert.Contains("public sealed class TestEntityDefaultValidator : AbstractValidator<TestEntity>", content);
    }

    [Fact]
    public void Generate_CreatesValidatorWithConstructor()
    {
        var manifest = JD.Domain.Modeling.Domain.Create("TestDomain")
            .Version(1, 0, 0)
            .Entity<TestEntity>()
            .Rules<TestEntity>(r => r
                .Invariant("NameRequired", x => !string.IsNullOrWhiteSpace(x.Name)))
            .BuildManifest();

        var context = CreateContext(manifest);
        var generator = new FluentValidationGenerator();
        var files = generator.Generate(context).ToList();

        var content = files[0].Content;
        Assert.Contains("public TestEntityDefaultValidator()", content);
    }

    [Fact]
    public void Generate_MapsNotEmptyRule()
    {
        var manifest = JD.Domain.Modeling.Domain.Create("TestDomain")
            .Version(1, 0, 0)
            .Entity<TestEntity>()
            .Rules<TestEntity>(r => r
                .Invariant("NameRequired", x => !string.IsNullOrWhiteSpace(x.Name))
                    .WithMessage("Name is required"))
            .BuildManifest();

        var context = CreateContext(manifest);
        var generator = new FluentValidationGenerator();
        var files = generator.Generate(context).ToList();

        var content = files[0].Content;
        Assert.Contains("RuleFor(x => x.Name)", content);
        Assert.Contains(".NotEmpty()", content);
        Assert.Contains("WithMessage(\"Name is required\")", content);
    }

    [Fact]
    public void Generate_MapsMaxLengthRule()
    {
        var manifest = JD.Domain.Modeling.Domain.Create("TestDomain")
            .Version(1, 0, 0)
            .Entity<TestEntity>()
            .Rules<TestEntity>(r => r
                .Invariant("NameLength", x => x.Name.Length <= 200)
                    .WithMessage("Name too long"))
            .BuildManifest();

        var context = CreateContext(manifest);
        var generator = new FluentValidationGenerator();
        var files = generator.Generate(context).ToList();

        var content = files[0].Content;
        Assert.Contains("RuleFor(x => x.Name)", content);
        Assert.Contains(".MaximumLength(200)", content);
    }

    [Fact]
    public void Generate_MapsGreaterThanOrEqualToRule()
    {
        var manifest = JD.Domain.Modeling.Domain.Create("TestDomain")
            .Version(1, 0, 0)
            .Entity<TestEntity>()
            .Rules<TestEntity>(r => r
                .Validator("CountValid", x => x.Count >= 0)
                    .WithMessage("Count must be non-negative"))
            .BuildManifest();

        var context = CreateContext(manifest);
        var generator = new FluentValidationGenerator();
        var files = generator.Generate(context).ToList();

        var content = files[0].Content;
        Assert.Contains("RuleFor(x => x.Count)", content);
        Assert.Contains(".GreaterThanOrEqualTo(0)", content);
    }

    [Fact]
    public void Generate_MapsSeverityToFluentValidationSeverity()
    {
        var manifest = JD.Domain.Modeling.Domain.Create("TestDomain")
            .Version(1, 0, 0)
            .Entity<TestEntity>()
            .Rules<TestEntity>(r => r
                .Invariant("NameRequired", x => !string.IsNullOrWhiteSpace(x.Name))
                    .WithSeverity(RuleSeverity.Warning))
            .BuildManifest();

        var context = CreateContext(manifest);
        var generator = new FluentValidationGenerator();
        var files = generator.Generate(context).ToList();

        var content = files[0].Content;
        Assert.Contains("WithSeverity(Severity.Warning)", content);
    }

    [Fact]
    public void Generate_CreatesValidatorForNamedRuleSet()
    {
        var manifest = JD.Domain.Modeling.Domain.Create("TestDomain")
            .Version(1, 0, 0)
            .Entity<TestEntity>()
            .Rules<TestEntity>("Create", r => r
                .Invariant("NameRequired", x => !string.IsNullOrWhiteSpace(x.Name)))
            .BuildManifest();

        var context = CreateContext(manifest);
        var generator = new FluentValidationGenerator();
        var files = generator.Generate(context).ToList();

        Assert.Single(files);
        Assert.Equal("TestEntityCreateValidator.g.cs", files[0].FileName);
        Assert.Contains("public sealed class TestEntityCreateValidator", files[0].Content);
    }

    [Fact]
    public void Generate_CreatesMultipleValidatorsForMultipleRuleSets()
    {
        var manifest = JD.Domain.Modeling.Domain.Create("TestDomain")
            .Version(1, 0, 0)
            .Entity<TestEntity>()
            .Rules<TestEntity>("Create", r => r
                .Invariant("NameRequired", x => !string.IsNullOrWhiteSpace(x.Name)))
            .Rules<TestEntity>("Update", r => r
                .Validator("CountValid", x => x.Count >= 0))
            .BuildManifest();

        var context = CreateContext(manifest);
        var generator = new FluentValidationGenerator();
        var files = generator.Generate(context).ToList();

        Assert.Equal(2, files.Count);
        Assert.Contains(files, f => f.FileName == "TestEntityCreateValidator.g.cs");
        Assert.Contains(files, f => f.FileName == "TestEntityUpdateValidator.g.cs");
    }

    [Fact]
    public void Generate_EscapesSpecialCharactersInMessages()
    {
        var manifest = JD.Domain.Modeling.Domain.Create("TestDomain")
            .Version(1, 0, 0)
            .Entity<TestEntity>()
            .Rules<TestEntity>(r => r
                .Invariant("NameRequired", x => !string.IsNullOrWhiteSpace(x.Name))
                    .WithMessage("Name \"must\" be provided"))
            .BuildManifest();

        var context = CreateContext(manifest);
        var generator = new FluentValidationGenerator();
        var files = generator.Generate(context).ToList();

        var content = files[0].Content;
        Assert.Contains("WithMessage(\"Name \\\"must\\\" be provided\")", content);
    }

    [Fact]
    public void Generate_UsesCustomNamespaceWhenProvided()
    {
        var manifest = JD.Domain.Modeling.Domain.Create("TestDomain")
            .Version(1, 0, 0)
            .Entity<TestEntity>()
            .Rules<TestEntity>(r => r
                .Invariant("NameRequired", x => !string.IsNullOrWhiteSpace(x.Name)))
            .BuildManifest();

        var properties = new Dictionary<string, string> { { "Namespace", "MyApp.Domain" } };
        var context = CreateContext(manifest, properties);
        var generator = new FluentValidationGenerator();
        var files = generator.Generate(context).ToList();

        var content = files[0].Content;
        Assert.Contains("namespace MyApp.Domain.Validators", content);
    }

    [Fact]
    public void Generate_UsesDefaultNamespaceWhenNotProvided()
    {
        var manifest = JD.Domain.Modeling.Domain.Create("TestDomain")
            .Version(1, 0, 0)
            .Entity<TestEntity>()
            .Rules<TestEntity>(r => r
                .Invariant("NameRequired", x => !string.IsNullOrWhiteSpace(x.Name)))
            .BuildManifest();

        var context = CreateContext(manifest);
        var generator = new FluentValidationGenerator();
        var files = generator.Generate(context).ToList();

        var content = files[0].Content;
        Assert.Contains("namespace TestDomain.Validators", content);
    }

    [Fact]
    public void Generate_IncludesIncludesComment()
    {
        var manifest = JD.Domain.Modeling.Domain.Create("TestDomain")
            .Version(1, 0, 0)
            .Entity<TestEntity>()
            .Rules<TestEntity>("Create", r => r
                .Invariant("NameRequired", x => !string.IsNullOrWhiteSpace(x.Name)))
            .BuildManifest();

        // Manually add an Include to the rule set for testing
        var ruleSet = manifest.RuleSets[0];
        var updatedRuleSet = new RuleSetManifest
        {
            Name = ruleSet.Name,
            TargetType = ruleSet.TargetType,
            Rules = ruleSet.Rules,
            Includes = new[] { "Default" }
        };
        var updatedManifest = new DomainManifest
        {
            Name = manifest.Name,
            Version = manifest.Version,
            Entities = manifest.Entities,
            RuleSets = new[] { updatedRuleSet }
        };

        var context = CreateContext(updatedManifest);
        var generator = new FluentValidationGenerator();
        var files = generator.Generate(context).ToList();

        var content = files[0].Content;
        Assert.Contains("// Includes: Default", content);
    }
}
